### ISSUE TITLE
"Advisory bike Lanes" in the us?

### ISSUE THREAD

**Issue by joeybab3** [streetcomplete/countrymetadata#13]
I was mapping bike lanes and realized that with the last update there is no longer the ability to mark a section of road as having dashed/advisory bike lanes. 

I saw the issues opened about some other countries which don't have that or were confusing and it looks like you are still doing research for country specific implementations of it, wanted to add some pictures of lanes here in California in case it helps.

![advisorylanes](https://user-images.githubusercontent.com/2829457/201203705-0dc55227-9f01-4c2d-9313-124e652da6de.jpg)

vs normal

![bikelane](https://user-images.githubusercontent.com/2829457/201203811-e2e9bc1d-8ad4-4fc3-81a2-a43ce75069f0.jpg)

Maybe I'm just misunderstanding the purpose of the dashed lane but I think it shouldn't have gone away here in the US

**Comment by westnordost** [comment]
The first picture is just a normal car traffic line I'd say.

**Comment by joeybab3** [comment]
> The first picture is just a normal car traffic line I'd say.
![Screenshot 2022-11-10 at 3 18 26 PM](https://user-images.githubusercontent.com/2829457/201226170-c2176844-ca20-48f9-b6fd-6f42b162e71e.png)
I'm referring to the dashed line on the left of the image, that is the part of the bike lane where cars are legally allowed to enter to complete a turn

**Comment by westnordost** [comment]
Yes, I referred to that as well.

**Comment by westnordost** [comment]
The concept of advisory bike lanes do not exist in the US as far as I know. What exists are sharrows, a very similar concept but without the dashed line.

**Comment by joeybab3** [comment]
It is still a bike lane though, in most cases these are not wide enough to fit a car, this one is because the city cannibalized a traffic lane to make a bike lane with a safety cushion next to it

**Comment by westnordost** [comment]
Should you find something in state legislation, feel free to comment here again or just create a PR.

Also pinging @1ec5 , he is also from California and interested in mapping (that).

**Comment by joeybab3** [comment]
I know they also attempted to do something closer to what I'm assuming is a proper advisory bike lane in San Diego but scrapped it: https://www.cbs8.com/article/news/local/drivers-education-needed-san-diegos-new-advisory-bike-lanes/509-f85184cc-4f8f-4d33-bf98-2a1ec1a2cf49

**Comment by westnordost** [comment]
Access Denied

**Comment by joeybab3** [comment]
Ahh region restrictions... 
here's two screencaps from it 
![Screenshot 2022-11-10 at 3 33 45 PM](https://user-images.githubusercontent.com/2829457/201227996-75c20afe-b126-4882-8bb8-fdddc705a773.png)
![Screenshot 2022-11-10 at 3 33 57 PM](https://user-images.githubusercontent.com/2829457/201227999-0de0b1d1-8f7b-4e9f-96b7-2c482dceaf64.png)

**Comment by westnordost** [comment]
Hm! This looks very much like a [2-1 road](https://en.wikipedia.org/wiki/2-1_road). These are indeed tagged as "advisory" cycleways.

In which state is this and do you have a source for that? I mean, not just a picture, but an article or the legislation or some road building manual etc.

**Comment by westnordost** [comment]
Oh wait, you mentioned that they scrapped it.

So, they built it, but then un-built it? Uhh. Would love to see the report though, because in Europe these things are getting more popular (hopefully based on studies and not whim).

**Comment by joeybab3** [comment]
They were scrapped in that specific instance because drivers didn't like them... but there are several experiments ongoing with them across the US apparently: https://www.fhwa.dot.gov/environment/bicycle_pedestrian/guidance/mutcd/dashed_bike_lanes.cfm

San Francisco appears to also have one 
https://www.presidio.gov/presidio-trust/planning/advisory-bike-lane-in-the-presidio
![image](https://user-images.githubusercontent.com/2829457/201228877-58ba25eb-d4f8-49c6-bf20-6b1959764f72.png)

**Comment by joeybab3** [comment]
Let me know if you need anything off either of those sites due to region restrictions...

**Comment by westnordost** [comment]
Drivers didn't like them, lol 🤣

**Comment by joeybab3** [comment]
> Drivers didn't like them, lol 🤣

Typical I know... To be fair the city just went and changed it one day without notifying people and these aren't exactly common here so all the people who lived on that street were up in arms

**Comment by westnordost** [comment]
> They were scrapped in that specific instance because drivers didn't like them... but there are several experiments ongoing with them across the US apparently: https://www.fhwa.dot.gov/environment/bicycle_pedestrian/guidance/mutcd/dashed_bike_lanes.cfm

Interesting! So this is indeed a nation-wide (or even wider?) standard? Pinging @1ec5 again because he is also a MUTCD guru.

**Comment by joeybab3** [comment]
That FHWA article would suggest that a federal standard may be upcoming or at least in consideration

**Comment by 1ec5** [comment]
> I'm referring to the dashed line on the left of the image, that is the part of the bike lane where cars are legally allowed to enter to complete a turn

[<img src="https://upload.wikimedia.org/wikipedia/commons/3/35/MUTCD_R4-4.svg" width="100" alt="R4-4" align="right">](https://commons.wikimedia.org/wiki/File:MUTCD_R4-4.svg)

These dashed lines near intersections are [a national standard](https://mutcd.fhwa.dot.gov/htm/2009r1r2r3/part9/fig9c_06_longdesc.htm) and incredibly common in California. I’ve been treating it as a short shared lane. Even though there isn’t a sharrow marking, cyclists do have to share the roadway with turning cars. I try to map these shared turn lanes whenever I see them, but it’s very annoying because a bunch of keys are involved (`cycleway`, `turn:lanes`, `bicycle:turn:lanes`, `change`). Thankfully, Lyft has been helping with these shared lanes as they improve coverage of cycling infrastructure in my area.

> That FHWA article would suggest that a federal standard may be upcoming or at least in consideration

Not necessarily. An experiment is just that. Based on the required traffic study’s findings, FHWA may issue an [interim approval](https://mutcd.fhwa.dot.gov/resources/interim_approval/ialistreq.htm), which could end up in a future edition of the MUTCD if it isn’t revoked in the meantime. Interim approvals are widespread enough to account for in our tagging schemes, but experiments are time-bound and sometimes a bit exotic, so I wouldn’t put too much emphasis on them.

**Comment by westnordost** [comment]
Okay, given that the 2-1 roads are experimental, would you say they are common enough that streetcomplete should support them or rather wait until (if) they become approved?

**Comment by 1ec5** [comment]
[This FHWA webpage](https://www.fhwa.dot.gov/environment/bicycle_pedestrian/guidance/mutcd/dashed_bike_lanes.cfm) lists five official experiments on dashed bike lanes. Unfortunately, the official ruling database doesn’t provide any detail on how many streets are involved in each experiment or for how long. Sometimes a traffic study involves only one street, but other times it can involve many streets to gather additional data points. I’d probably look at whether the press describes any trends around this treatment or if it’s always described as a one-off, exotic experiment. I think it’s safe to presume that an experiment is rare unless there’s evidence otherwise.

**Comment by westnordost** [comment]
Okay thank you. So I will close this for now but also add the information from this ticket to the repo
